index.js, readme.md, test.js
- Add `autoStart` `boolean` option.
- Add `.start()` method.
- Add `.pause()` method.
- Add tests.
If this is ok, additional suggestions (not in this PR) for later:
... or `status` getter returns one of this enum: `'idle'`, `'empty'`, `'started'`, `'paused'`
=> Add execution control (fix #21)

bench.js, index.js, package.json, readme.md, test.js
There are cases where some sync operation should be queued after an async op.
Normally you'd do:
```js
return asyncOp.then(() => syncOp());
```
but this doesn't fit every case; `syncOp()` might belong to a separate view.
Wrapping the queue task added, in a resolver solves this.
`Promise.resolve(fn())` —» `fn` can either return a promise or a value.
=> Add ability to queue sync/async mixed tasks

index.js
Fixes #32 
Because we accept synchronous functions, they may throw an error. So `p-queue` crashes because there's nothing to handle that error.
=> Reject on sync function error

index.js, test.js
The previous condition is not sufficient to call `_resolveEmpty `.
=> Fix `.onEmpty()` not always resolving when size is zero

index.js, readme.md, test.js
Similar in spirit to a proprosal in #41.  This doesn't necessitate the use case mentioned in that issue, but it would provide a tool which could be used for that purpose.  My motivation for this would be to have a hook into the processing without requiring an external interval to poll a queue instance.
=> Add `active` event

index.js, package.json, readme.md, test.js
As outlined in https://github.com/sindresorhus/p-queue/issues/55#issuecomment-467331355 - this replaces the `events` dependency with `eventemitter3`, making this module work without issues in browsers and react native environments.
Fixes #55
=> Use `eventemitter3` module instead of Node.js EventEmitter

package.json, source/options.ts
This fixes #66.  In our TypeScript npm modules, we're unable to use this library because of the bug in #66.  This PR does a few things:
- Bumps the required TypeScript version to `3.5.1`
- Moves to a `~` range specifier, as the TypeScript compiler makes breaking changes in minor relases
- Loosens the type required for `DefaultAddOptions`.  I'm not super confident with this particular change, so it could use another set of 👀
=> Fix TypeScript 3.5 compatibility

package.json
Upgrade to 6.0.0 breaks module resolution due to missing index file that was previously at the package root, but now it is included within the `dist` directory. Offending changes introduced by modification of `files` package.json entry: https://github.com/sindresorhus/p-queue/commit/a9d3ad9996d0f6cc91bb63676bf43ef2c764971b
Solved by the inclusion of `main` package.json field which points to the correct entry point inside the `dist` folder.
Error:
```sh
internal/modules/cjs/loader.js:613
throw err;
^
Error: Cannot find module 'p-queue'
Require stack:
- [REDACTED]\index.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
at Function.Module._load (internal/modules/cjs/loader.js:526:27)
at Module.require (internal/modules/cjs/loader.js:666:19)
at require …
```
=> Add missing package.json main field

source/index.ts
Started seeing this error popup
```
node_modules/p-queue/dist/index.d.ts:1:8 - error TS1259: Module '"/node_modules/eventemitter3/index"' can only be default-imported using the 'esModuleInterop' flag
1 import EventEmitter from 'eventemitter3';
~~~~~~~~~~~~
node_modules/eventemitter3/index.d.ts:64:1
64 export = EventEmitter;
~~~~~~~~~~~~~~~~~~~~~~
This module is declared with using 'export =', and can only be used with a default import when using the 'esModuleInterop' flag.
```
=> TypeScript - Fix import for dependencies with no default export

source/index.ts
With latest v6 changes, in order to define a custom `Queue` class, one will need to do the following
```ts
import { Queue } from 'p-queue/dist/queue';
import { QueueAddOptions } from 'p-queue/dist/options';
class CustomQueue implements Queue<NamedQueueOptions> {}
```
This PR will simplify this to
```ts
import { Queue, QueueAddOption } from 'p-queue';
class CustomQueue implements Queue<NamedQueueOptions> {}
```
=> TypeScript - Properly export interfaces

package.json, readme.md, source/index.ts, source/options.ts, test/test.ts
See questions in #74 - this is one possible option with a test and documentation fix for the throwOnTimeout default.
I'm not well-versed in typescript, but it seems like there's probably a better means for optional parameter lookups than this?
Fixes #74
=> Correct the documented default for the `throwOnTimeout` option

source/index.ts
This fixes an issue where `throwOnTimeout` would not be respected due to a typo (`throwOnTimout` vs `throwOnTimeout`).
This wasn't picked up by typings as the typings are incredibly loose, where any property of an object is a valid property. I'd suggest improving these typings (might do this in a future PR).
=> Fix typo in options logic when adding a task

source/index.ts, test/test.ts
The built TS file attempts to access `ptimeout_1.default.TimeoutError()` which under some conditions (IE: inside of Electron) returns undefined.
- Importing `pTimeout` and `TimeoutError` separately
=> Fix importing `TimeoutError`

package.json, readme.md, source/index.ts, source/options.ts, source/priority-queue.ts, source/queue.ts, test/test.ts
Thanks for a great and useful library.
We use `p-queue` to totally order all of the web requests our app makes. However this means that there is a risk that when the user closes the tab, there is some work left pending in the promise queue.
We use priority to discern between important requests (eg. a user action) and unimportant requests (eg. updating something unimportant in the background).
We use an `onbeforeunload` hook to warn the user that they could lose changes if `queue.size > 0`. However it would be an improvement to user experience if we could only warn them if the queue contains very important actions (based on priority). This is what motivated me to implement `sizeBy`, which takes the same priority options as `add`, and filters the results.
Interested to hear what you think!
=> Add `.sizeBy()` method to find queue size by priority

readme.md, source/index.ts, test/test.ts
following #107 
I added an `idle` event
Emitted when the queue becomes empty, and all promises have completed; `queue.size === 0 && queue.pending === 0`.
```js
const delay = require('delay');
const {default: PQueue} = require('p-queue');
const queue = new PQueue();
queue.on('idle', () => {
console.log(`Queue is idle.  Size: ${queue.size}  Pending: ${queue.pending}`);
});
const job1 = queue.add(() => delay(2000));
const job2 = queue.add(() => delay(500));
await job1;
await job2;
// => 'Queue is idle.  Size: 0  Pending: 0'
await queue.add(() => delay(600));
// => 'Queue is idle.  Size: 0  Pending: 0'
```
=> Add `idle` event

readme.md
Updates `carryoverConcurrencyCount` documentation as discussed in issue #99 .
=> Clarify `carryoverConcurrencyCount` documentation

readme.md, source/index.ts, test/test.ts
Related to https://github.com/sindresorhus/p-queue/issues/107
I needed some way to listen to changes in the amount of work in the PQueue.
One event is emitted when work is added, the other when work is completed.
=> Add `add` and `next` events

readme.md, source/index.ts, test/test.ts
Returns a promise that settles when the queue size is less than the given limit; `queue.size < limit`.
If you want to avoid having the queue grow beyond a certain size you can `await queue.onSizeLessThan()` before
adding a new item.
Note that this only limits the number of items waiting to start; there could still be up to `concurrency` jobs
already running that this call does not include in its calculation.
=> Add `.onSizeLessThan()` helper method

.github/workflows/main.yml, readme.md, source/index.ts, source/options.ts, source/priority-queue.ts, test/test.ts
=> Support `AbortController`

readme.md, source/index.ts, source/options.ts, source/priority-queue.ts, source/queue.ts, test/test.ts
Fixes #208 - add a `uid` to track the promise functions and update the priority on any promise.
also add a new event `started` to notify when a promise function is executed.
=> Add `.setPriority()` for updating priority of a queued promise function
